import { EXTRA_PLAYERS } from "./extra-players.js";
import { GENERATED_DRAFT_SQUADS, GENERATED_PLAYERS } from "./generated-world-cup-data.js";

export const ROLE_ORDER = ["batsman", "wicketkeeper", "bowler"];

export const ROLE_LABELS = {
  batsman: "Batsman",
  wicketkeeper: "WK",
  bowler: "Bowler",
};

export const REQUIRED_ROLES = {
  batsman: 1,
  wicketkeeper: 1,
  bowler: 1,
};

const BASE_DRAFT_SQUADS = [
  {
    id: "india-1983",
    label: "India 1983",
    country: "India",
    year: 1983,
    note: "Swing, grit, and a lineup that still believes every total is defendable.",
  },
  {
    id: "pakistan-1992",
    label: "Pakistan 1992",
    country: "Pakistan",
    year: 1992,
    note: "Peak cornered-tigers energy with elite fast bowling upside.",
  },
  {
    id: "sri-lanka-1996",
    label: "Sri Lanka 1996",
    country: "Sri Lanka",
    year: 1996,
    note: "Aggressive ODI batting before most teams had caught up tactically.",
  },
  {
    id: "west-indies-1996",
    label: "West Indies 1996",
    country: "West Indies",
    year: 1996,
    note: "Silk in the top order and serious hostility with the new ball.",
  },
  {
    id: "australia-1999",
    label: "Australia 1999",
    country: "Australia",
    year: 1999,
    note: "Tournament steel, ruthless bowling, and no panic in tight finishes.",
  },
  {
    id: "south-africa-1999",
    label: "South Africa 1999",
    country: "South Africa",
    year: 1999,
    note: "Loaded with all-round quality and relentless seam options.",
  },
  {
    id: "india-2011",
    label: "India 2011",
    country: "India",
    year: 2011,
    note: "Control through the middle overs and batting built for pressure chases.",
  },
  {
    id: "australia-2015",
    label: "Australia 2015",
    country: "Australia",
    year: 2015,
    note: "Fast-scoring batting backed by left-arm pace and tournament punch.",
  },
  {
    id: "new-zealand-2019",
    label: "New Zealand 2019",
    country: "New Zealand",
    year: 2019,
    note: "Calm leadership and a bowling group that keeps dragging games deep.",
  },
  {
    id: "england-2019",
    label: "England 2019",
    country: "England",
    year: 2019,
    note: "Explosive white-ball batting with enough wicket-takers to back it up.",
  },
  {
    id: "bangladesh-2019",
    label: "Bangladesh 2019",
    country: "Bangladesh",
    year: 2019,
    note: "A golden modern ODI core with elite all-round production.",
  },
  {
    id: "india-2023",
    label: "India 2023",
    country: "India",
    year: 2023,
    note: "Top-order command and a fast-bowling attack that can bury a chase.",
  },
  {
    id: "pakistan-2023",
    label: "Pakistan 2023",
    country: "Pakistan",
    year: 2023,
    note: "Stylish batting and attack leaders who can crack open powerplays.",
  },
  {
    id: "afghanistan-2023",
    label: "Afghanistan 2023",
    country: "Afghanistan",
    year: 2023,
    note: "Spin-heavy threat with genuine upset potential and fearless batting moments.",
  },
  {
    id: "zimbabwe-1999",
    label: "Zimbabwe 1999",
    country: "Zimbabwe",
    year: 1999,
    note: "A golden Zimbabwe side with proper all-round stubbornness and upset history.",
  },
  {
    id: "kenya-2003",
    label: "Kenya 2003",
    country: "Kenya",
    year: 2003,
    note: "The semifinal run side that proved disciplined ODI cricket could punch above its weight.",
  },
  {
    id: "bermuda-2007",
    label: "Bermuda 2007",
    country: "Bermuda",
    year: 2007,
    note: "A landmark qualifier squad with experienced club-cricket steel.",
  },
  {
    id: "canada-2011",
    label: "Canada 2011",
    country: "Canada",
    year: 2011,
    note: "A multinational ODI unit with hitters, seamers, and plenty of unpredictability.",
  },
  {
    id: "ireland-2011",
    label: "Ireland 2011",
    country: "Ireland",
    year: 2011,
    note: "The giant-killing Irish core that could turn one session into chaos.",
  },
  {
    id: "scotland-2015",
    label: "Scotland 2015",
    country: "Scotland",
    year: 2015,
    note: "A balanced modern Scotland side with real batting craft and honest seam depth.",
  },
  {
    id: "uae-2015",
    label: "UAE 2015",
    country: "United Arab Emirates",
    year: 2015,
    note: "An associate squad with experienced middle-order batting and crafty spin support.",
  },
  {
    id: "namibia-2003",
    label: "Namibia 2003",
    country: "Namibia",
    year: 2003,
    note: "Namibia's breakthrough World Cup side, gritty and highly motivated.",
  },
  {
    id: "netherlands-2023",
    label: "Netherlands 2023",
    country: "Netherlands",
    year: 2023,
    note: "A smart Dutch side with modern all-round depth and real tactical flexibility.",
  },
];

const BASE_PLAYER_POOL = [
  {
    id: "sunil-gavaskar",
    name: "Sunil Gavaskar",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "batsman",
    batting: 87,
    bowling: 12,
    blurb: "Technical certainty for tricky surfaces and pressure starts.",
  },
  {
    id: "kris-srikkanth",
    name: "Kris Srikkanth",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "batsman",
    batting: 82,
    bowling: 20,
    blurb: "Chaos-up-top intent before that became the white-ball default.",
  },
  {
    id: "mohinder-amarnath",
    name: "Mohinder Amarnath",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "batsman",
    batting: 80,
    bowling: 72,
    blurb: "A pressure sponge who still gives you usable overs.",
  },
  {
    id: "syed-kirmani",
    name: "Syed Kirmani",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "wicketkeeper",
    batting: 72,
    bowling: 0,
    blurb: "Safe hands and composed lower-order resistance.",
  },
  {
    id: "kapil-dev",
    name: "Kapil Dev",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "bowler",
    batting: 84,
    bowling: 88,
    blurb: "Leadership, seam, and one of ODI cricket's original game-breakers.",
  },
  {
    id: "javed-miandad",
    name: "Javed Miandad",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "batsman",
    batting: 90,
    bowling: 18,
    blurb: "Street-smart control and total command of a chase.",
  },
  {
    id: "inzamam-ul-haq",
    name: "Inzamam-ul-Haq",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "batsman",
    batting: 89,
    bowling: 12,
    blurb: "Big-tournament timing with heavy middle-order presence.",
  },
  {
    id: "aamir-sohail",
    name: "Aamir Sohail",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "batsman",
    batting: 82,
    bowling: 18,
    blurb: "Left-handed tempo setter with strong ODI range.",
  },
  {
    id: "moin-khan",
    name: "Moin Khan",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "wicketkeeper",
    batting: 76,
    bowling: 0,
    blurb: "Lower-order scrapper with sharp glovework.",
  },
  {
    id: "imran-khan",
    name: "Imran Khan",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "bowler",
    batting: 83,
    bowling: 91,
    blurb: "Aura, new-ball discipline, and champion-level nerve.",
  },
  {
    id: "wasim-akram",
    name: "Wasim Akram",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "bowler",
    batting: 54,
    bowling: 96,
    blurb: "Reverse swing royalty and a complete ODI fast-bowling weapon.",
  },
  {
    id: "waqar-younis",
    name: "Waqar Younis",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "bowler",
    batting: 30,
    bowling: 91,
    blurb: "Pace, dip, yorkers, and stump-shattering endings.",
  },
  {
    id: "aravinda-de-silva",
    name: "Aravinda de Silva",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "batsman",
    batting: 92,
    bowling: 34,
    blurb: "The calm genius behind Sri Lanka's ODI leap forward.",
  },
  {
    id: "sanath-jayasuriya",
    name: "Sanath Jayasuriya",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "batsman",
    batting: 93,
    bowling: 76,
    blurb: "A powerplay revolution in human form.",
  },
  {
    id: "asaranka-gurusinha",
    name: "Asanka Gurusinha",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "batsman",
    batting: 80,
    bowling: 12,
    blurb: "Glue batting that let the stars attack around him.",
  },
  {
    id: "romesh-kaluwitharana",
    name: "Romesh Kaluwitharana",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "wicketkeeper",
    batting: 83,
    bowling: 0,
    blurb: "A wicketkeeper-opener who helped redefine ODI starts.",
  },
  {
    id: "muttiah-muralitharan",
    name: "Muttiah Muralitharan",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "bowler",
    batting: 22,
    bowling: 95,
    blurb: "Middle-over spin pressure that changes how innings breathe.",
  },
  {
    id: "chaminda-vaas",
    name: "Chaminda Vaas",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "bowler",
    batting: 38,
    bowling: 89,
    blurb: "Left-arm seam and economy that squeezes plans dry.",
  },
  {
    id: "brian-lara",
    name: "Brian Lara",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "batsman",
    batting: 97,
    bowling: 10,
    blurb: "A batting genius with the kind of ceiling only superstars get.",
  },
  {
    id: "shivnarine-chanderpaul",
    name: "Shivnarine Chanderpaul",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "batsman",
    batting: 86,
    bowling: 18,
    blurb: "Unorthodox shape, highly orthodox run production.",
  },
  {
    id: "carl-hooper",
    name: "Carl Hooper",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "batsman",
    batting: 84,
    bowling: 72,
    blurb: "A smooth all-round package with extra off-spin utility.",
  },
  {
    id: "junior-murray",
    name: "Junior Murray",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "wicketkeeper",
    batting: 76,
    bowling: 0,
    blurb: "Functional lower-order runs and tidy keeping.",
  },
  {
    id: "curtly-ambrose",
    name: "Curtly Ambrose",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "bowler",
    batting: 20,
    bowling: 92,
    blurb: "Bounce, menace, and lengths that felt permanently awkward.",
  },
  {
    id: "courtney-walsh",
    name: "Courtney Walsh",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "bowler",
    batting: 22,
    bowling: 91,
    blurb: "Relentless seam bowling with big-tournament control.",
  },
  {
    id: "ian-bishop",
    name: "Ian Bishop",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "bowler",
    batting: 24,
    bowling: 87,
    blurb: "Smart pace bowling with lift and late-over value.",
  },
  {
    id: "ricky-ponting",
    name: "Ricky Ponting",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "batsman",
    batting: 97,
    bowling: 16,
    blurb: "A final-boss No. 3 who earned his place in the 95-plus tier.",
  },
  {
    id: "michael-bevan",
    name: "Michael Bevan",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "batsman",
    batting: 88,
    bowling: 26,
    blurb: "The original chase mechanic in human form.",
  },
  {
    id: "steve-waugh",
    name: "Steve Waugh",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "batsman",
    batting: 86,
    bowling: 68,
    blurb: "Tournament steel and deceptively useful overs.",
  },
  {
    id: "adam-gilchrist",
    name: "Adam Gilchrist",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "wicketkeeper",
    batting: 95,
    bowling: 0,
    blurb: "A wicketkeeper-opener who always threatened to break the script.",
  },
  {
    id: "shane-warne",
    name: "Shane Warne",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "bowler",
    batting: 36,
    bowling: 96,
    blurb: "One of the few bowlers who belongs comfortably in the 95-plus tier.",
  },
  {
    id: "glenn-mcgrath",
    name: "Glenn McGrath",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "bowler",
    batting: 18,
    bowling: 95,
    blurb: "Metronomic accuracy and major-event suffocation.",
  },
  {
    id: "damien-fleming",
    name: "Damien Fleming",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "bowler",
    batting: 24,
    bowling: 84,
    blurb: "Swing and control that fit beautifully around the headline stars.",
  },
  {
    id: "herschelle-gibbs",
    name: "Herschelle Gibbs",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "batsman",
    batting: 90,
    bowling: 14,
    blurb: "Shot range and powerplay damage in equal measure.",
  },
  {
    id: "jacques-kallis",
    name: "Jacques Kallis",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "batsman",
    batting: 92,
    bowling: 81,
    blurb: "Structure with the bat, control with the ball, value everywhere.",
  },
  {
    id: "jonty-rhodes",
    name: "Jonty Rhodes",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "batsman",
    batting: 83,
    bowling: 22,
    blurb: "A sharp ODI middle-order operator who keeps tempo honest.",
  },
  {
    id: "mark-boucher",
    name: "Mark Boucher",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "wicketkeeper",
    batting: 84,
    bowling: 0,
    blurb: "Dependable keeping with useful lower-order force.",
  },
  {
    id: "lance-klusener",
    name: "Lance Klusener",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "bowler",
    batting: 86,
    bowling: 84,
    blurb: "Brute-force finishing and a serious seam-up wicket threat.",
  },
  {
    id: "shaun-pollock",
    name: "Shaun Pollock",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "bowler",
    batting: 72,
    bowling: 89,
    blurb: "Line, length, brains, and genuine batting depth.",
  },
  {
    id: "allan-donald",
    name: "Allan Donald",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "bowler",
    batting: 18,
    bowling: 90,
    blurb: "Hard pace and relentless hostility through the deck.",
  },
  {
    id: "sachin-tendulkar",
    name: "Sachin Tendulkar",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "batsman",
    batting: 98,
    bowling: 28,
    blurb: "Run-making certainty and a true 95-plus all-timer.",
  },
  {
    id: "virender-sehwag",
    name: "Virender Sehwag",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "batsman",
    batting: 91,
    bowling: 10,
    blurb: "An opening overs detonator with no patience for sighters.",
  },
  {
    id: "virat-kohli",
    name: "Virat Kohli",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "batsman",
    batting: 94,
    bowling: 8,
    blurb: "The chase engine you trust when the required rate tightens.",
  },
  {
    id: "ms-dhoni",
    name: "MS Dhoni",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "wicketkeeper",
    batting: 92,
    bowling: 0,
    blurb: "Finishing brains, finishing power, and permanent calm.",
  },
  {
    id: "yuvraj-singh",
    name: "Yuvraj Singh",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "batsman",
    batting: 90,
    bowling: 78,
    blurb: "A tournament-shaping all-round ODI package.",
  },
  {
    id: "zaheer-khan",
    name: "Zaheer Khan",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "bowler",
    batting: 22,
    bowling: 89,
    blurb: "New-ball thinking and a brilliant slower-ball toolkit.",
  },
  {
    id: "harbhajan-singh",
    name: "Harbhajan Singh",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "bowler",
    batting: 30,
    bowling: 86,
    blurb: "A middle-over off-spin pressure valve with personality.",
  },
  {
    id: "david-warner",
    name: "David Warner",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "batsman",
    batting: 92,
    bowling: 10,
    blurb: "Powerplay damage that changes field settings instantly.",
  },
  {
    id: "steve-smith",
    name: "Steve Smith",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "batsman",
    batting: 93,
    bowling: 18,
    blurb: "Control, tempo, and run accumulation from awkward angles.",
  },
  {
    id: "glenn-maxwell",
    name: "Glenn Maxwell",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "batsman",
    batting: 89,
    bowling: 73,
    blurb: "High-variance batting with very real off-spin value.",
  },
  {
    id: "brad-haddin",
    name: "Brad Haddin",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "wicketkeeper",
    batting: 82,
    bowling: 0,
    blurb: "Busy ODI keeper-batter with final-stage edge.",
  },
  {
    id: "mitchell-starc",
    name: "Mitchell Starc",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "bowler",
    batting: 36,
    bowling: 95,
    blurb: "Left-arm thunder and one of ODI cricket's true 95-plus bowlers.",
  },
  {
    id: "mitchell-johnson",
    name: "Mitchell Johnson",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "bowler",
    batting: 48,
    bowling: 88,
    blurb: "Pace and intimidation with extra lower-order sting.",
  },
  {
    id: "james-faulkner",
    name: "James Faulkner",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "bowler",
    batting: 79,
    bowling: 80,
    blurb: "A proper white-ball all-round specialist.",
  },
  {
    id: "kane-williamson",
    name: "Kane Williamson",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "batsman",
    batting: 93,
    bowling: 18,
    blurb: "Low pulse, high IQ, ideal for knockout cricket.",
  },
  {
    id: "martin-guptill",
    name: "Martin Guptill",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "batsman",
    batting: 88,
    bowling: 8,
    blurb: "A clean ball-striker who can flatten group games quickly.",
  },
  {
    id: "ross-taylor",
    name: "Ross Taylor",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "batsman",
    batting: 89,
    bowling: 10,
    blurb: "Middle-order control with strong spin hitting instincts.",
  },
  {
    id: "tom-latham",
    name: "Tom Latham",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "wicketkeeper",
    batting: 84,
    bowling: 0,
    blurb: "Reliable keeping with left-handed batting balance.",
  },
  {
    id: "jimmy-neesham",
    name: "Jimmy Neesham",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "batsman",
    batting: 78,
    bowling: 74,
    blurb: "A utility all-round option who can change an innings late.",
  },
  {
    id: "trent-boult",
    name: "Trent Boult",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "bowler",
    batting: 26,
    bowling: 90,
    blurb: "Early swing and clever angles for white-ball control.",
  },
  {
    id: "tim-southee",
    name: "Tim Southee",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "bowler",
    batting: 42,
    bowling: 87,
    blurb: "New-ball craft and valuable late-order hitting.",
  },
  {
    id: "lockie-ferguson",
    name: "Lockie Ferguson",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "bowler",
    batting: 18,
    bowling: 88,
    blurb: "High pace through the middle overs with wicket-taking upside.",
  },
  {
    id: "joe-root",
    name: "Joe Root",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "batsman",
    batting: 92,
    bowling: 22,
    blurb: "The organizer who makes aggressive batting cards feel stable.",
  },
  {
    id: "jason-roy",
    name: "Jason Roy",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "batsman",
    batting: 88,
    bowling: 8,
    blurb: "Front-foot aggression that forces defensive bowling plans early.",
  },
  {
    id: "ben-stokes",
    name: "Ben Stokes",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "batsman",
    batting: 91,
    bowling: 79,
    blurb: "One of white-ball cricket's premier clutch all-rounders.",
  },
  {
    id: "jos-buttler",
    name: "Jos Buttler",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "wicketkeeper",
    batting: 93,
    bowling: 0,
    blurb: "Late-overs violence with a premium keeper-batter profile.",
  },
  {
    id: "eoin-morgan",
    name: "Eoin Morgan",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "batsman",
    batting: 88,
    bowling: 6,
    blurb: "Leadership and match-up aggression in the middle order.",
  },
  {
    id: "chris-woakes",
    name: "Chris Woakes",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "bowler",
    batting: 74,
    bowling: 83,
    blurb: "Quality seam bowling with genuine batting depth.",
  },
  {
    id: "jofra-archer",
    name: "Jofra Archer",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "bowler",
    batting: 26,
    bowling: 91,
    blurb: "High pace and high leverage in the biggest overs.",
  },
  {
    id: "adil-rashid",
    name: "Adil Rashid",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "bowler",
    batting: 18,
    bowling: 88,
    blurb: "Attacking leg spin that buys wickets instead of just control.",
  },
  {
    id: "tamim-iqbal",
    name: "Tamim Iqbal",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "batsman",
    batting: 87,
    bowling: 8,
    blurb: "An ODI anchor-opener with enough power to own the arc.",
  },
  {
    id: "shakib-al-hasan",
    name: "Shakib Al Hasan",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "batsman",
    batting: 92,
    bowling: 90,
    blurb: "A long-time ICC No. 1 all-round benchmark and a monster ODI value pick.",
  },
  {
    id: "mushfiqur-rahim",
    name: "Mushfiqur Rahim",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "wicketkeeper",
    batting: 89,
    bowling: 0,
    blurb: "Busy, high-skill batting with dependable keeping.",
  },
  {
    id: "mahmudullah",
    name: "Mahmudullah",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "batsman",
    batting: 84,
    bowling: 71,
    blurb: "A reliable finishing bat with real off-spin utility.",
  },
  {
    id: "mashrafe-mortaza",
    name: "Mashrafe Mortaza",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "bowler",
    batting: 58,
    bowling: 82,
    blurb: "Leadership and seam craft more than raw pace by this stage.",
  },
  {
    id: "mustafizur-rahman",
    name: "Mustafizur Rahman",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "bowler",
    batting: 22,
    bowling: 86,
    blurb: "Cutters, angle, and death-overs discomfort.",
  },
  {
    id: "mohammad-saifuddin",
    name: "Mohammad Saifuddin",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "bowler",
    batting: 69,
    bowling: 74,
    blurb: "Lower-order runs and functional seam support.",
  },
  {
    id: "rohit-sharma",
    name: "Rohit Sharma",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "batsman",
    batting: 94,
    bowling: 10,
    blurb: "A six-hitting starter pistol for ODI innings.",
  },
  {
    id: "shubman-gill",
    name: "Shubman Gill",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "batsman",
    batting: 91,
    bowling: 8,
    blurb: "Elegant modern ODI tempo with full-field scoring range.",
  },
  {
    id: "shreyas-iyer",
    name: "Shreyas Iyer",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "batsman",
    batting: 88,
    bowling: 6,
    blurb: "Strong pace-hitting through the middle overs.",
  },
  {
    id: "kl-rahul",
    name: "KL Rahul",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "wicketkeeper",
    batting: 84,
    bowling: 0,
    blurb: "A calm ODI consolidator with tidy glovework.",
  },
  {
    id: "ravindra-jadeja",
    name: "Ravindra Jadeja",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "bowler",
    batting: 78,
    bowling: 86,
    blurb: "Spin squeeze, batting control, and complete all-round balance.",
  },
  {
    id: "jasprit-bumrah",
    name: "Jasprit Bumrah",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "bowler",
    batting: 24,
    bowling: 95,
    blurb: "A shape-shifting ODI spell machine in the true superstar bracket.",
  },
  {
    id: "mohammed-shami",
    name: "Mohammed Shami",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "bowler",
    batting: 22,
    bowling: 91,
    blurb: "Seam, swing, and wicket bursts that crack games open fast.",
  },
  {
    id: "babar-azam",
    name: "Babar Azam",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "batsman",
    batting: 93,
    bowling: 8,
    blurb: "Pure timing and tempo control through the heart of an ODI innings.",
  },
  {
    id: "fakhar-zaman",
    name: "Fakhar Zaman",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "batsman",
    batting: 86,
    bowling: 8,
    blurb: "A left-handed disruptor with big-innings upside.",
  },
  {
    id: "saud-shakeel",
    name: "Saud Shakeel",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "batsman",
    batting: 82,
    bowling: 6,
    blurb: "A calmer accumulator when the innings needs structure.",
  },
  {
    id: "mohammad-rizwan",
    name: "Mohammad Rizwan",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "wicketkeeper",
    batting: 90,
    bowling: 0,
    blurb: "Intensity, consistency, and high-volume ODI running.",
  },
  {
    id: "shadab-khan",
    name: "Shadab Khan",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "bowler",
    batting: 79,
    bowling: 78,
    blurb: "Useful leg spin with genuine batting upside.",
  },
  {
    id: "shaheen-afridi",
    name: "Shaheen Afridi",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "bowler",
    batting: 28,
    bowling: 90,
    blurb: "New-ball menace with left-arm angle and late inswing.",
  },
  {
    id: "haris-rauf",
    name: "Haris Rauf",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "bowler",
    batting: 20,
    bowling: 87,
    blurb: "Speed and hard lengths that create wickets in clumps.",
  },
  {
    id: "rahmanullah-gurbaz",
    name: "Rahmanullah Gurbaz",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "wicketkeeper",
    batting: 86,
    bowling: 0,
    blurb: "A fearless keeper-opener with genuine powerplay upside.",
  },
  {
    id: "ibrahim-zadran",
    name: "Ibrahim Zadran",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "batsman",
    batting: 84,
    bowling: 6,
    blurb: "Measured ODI batting with enough range to bat deep.",
  },
  {
    id: "hashmatullah-shahidi",
    name: "Hashmatullah Shahidi",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "batsman",
    batting: 82,
    bowling: 10,
    blurb: "An innings stabilizer who keeps collapses from cascading.",
  },
  {
    id: "mohammad-nabi",
    name: "Mohammad Nabi",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "bowler",
    batting: 80,
    bowling: 76,
    blurb: "A complete ODI all-round operator with veteran skill.",
  },
  {
    id: "rashid-khan",
    name: "Rashid Khan",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "bowler",
    batting: 62,
    bowling: 92,
    blurb: "A wrist-spin strike force who changes the shape of an innings.",
  },
  {
    id: "mujeeb-ur-rahman",
    name: "Mujeeb Ur Rahman",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "bowler",
    batting: 24,
    bowling: 84,
    blurb: "Powerplay spin and awkward angles from ball one.",
  },
];

export const DRAFT_SQUADS = [...BASE_DRAFT_SQUADS, ...GENERATED_DRAFT_SQUADS].sort(
  (left, right) => left.year - right.year || left.country.localeCompare(right.country),
);

export const PLAYER_POOL = [...BASE_PLAYER_POOL, ...EXTRA_PLAYERS, ...GENERATED_PLAYERS];

export const TOURNAMENT_OPPONENTS = [
  {
    id: "bangladesh-2019",
    label: "Bangladesh 2019",
    shortName: "Bangladesh",
    stage: "Group Stage A",
    batting: 82,
    bowling: 80,
    overall: 80,
    pressure: 0,
    note: "A modern ODI side with serious all-round depth and no soft overs.",
  },
  {
    id: "india-1983",
    label: "India 1983",
    shortName: "India",
    stage: "Group Stage B",
    batting: 81,
    bowling: 83,
    overall: 82,
    pressure: 1,
    note: "They make you earn everything and still believe in every chase.",
  },
  {
    id: "pakistan-1992",
    label: "Pakistan 1992",
    shortName: "Pakistan",
    stage: "Group Stage C",
    batting: 84,
    bowling: 87,
    overall: 85,
    pressure: 2,
    note: "Swing, swagger, and a pace unit that can turn the lights out.",
  },
  {
    id: "south-africa-1999",
    label: "South Africa 1999",
    shortName: "South Africa",
    stage: "Quarter-final",
    batting: 89,
    bowling: 89,
    overall: 89,
    pressure: 5,
    note: "Balanced, athletic, and packed with wicket-taking options.",
  },
  {
    id: "india-2011",
    label: "India 2011",
    shortName: "India",
    stage: "Semi-final",
    batting: 92,
    bowling: 88,
    overall: 92,
    pressure: 6,
    note: "Elite chase control backed by experienced middle-overs bowling.",
  },
  {
    id: "australia-1999",
    label: "Australia 1999",
    shortName: "Australia",
    stage: "Final",
    batting: 92,
    bowling: 93,
    overall: 94,
    pressure: 8,
    note: "A champion side with superstar bowling and no emotional drop-off.",
  },
];
