export const EXTRA_PLAYERS = [
  {
    id: "yashpal-sharma",
    name: "Yashpal Sharma",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "batsman",
    batting: 81,
    bowling: 10,
    blurb: "Middle-order resilience with proper World Cup nerve.",
  },
  {
    id: "sandeep-patil",
    name: "Sandeep Patil",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "batsman",
    batting: 83,
    bowling: 12,
    blurb: "An aggressive stroke-maker who could flip a one-day innings.",
  },
  {
    id: "kirti-azad",
    name: "Kirti Azad",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "batsman",
    batting: 73,
    bowling: 64,
    blurb: "A useful hybrid option with handy middle-over spin.",
  },
  {
    id: "roger-binny",
    name: "Roger Binny",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "bowler",
    batting: 71,
    bowling: 81,
    blurb: "Seam movement and valuable lower-order runs.",
  },
  {
    id: "madan-lal",
    name: "Madan Lal",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "bowler",
    batting: 66,
    bowling: 79,
    blurb: "Competitive seam bowling with big-moment stubbornness.",
  },
  {
    id: "balwinder-sandhu",
    name: "Balwinder Sandhu",
    squadId: "india-1983",
    team: "India",
    year: 1983,
    role: "bowler",
    batting: 28,
    bowling: 76,
    blurb: "Swing bowling that could do damage before the batters settled.",
  },
  {
    id: "ramiz-raja",
    name: "Ramiz Raja",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "batsman",
    batting: 84,
    bowling: 8,
    blurb: "An opener who brought shape and tempo to ODI starts.",
  },
  {
    id: "saleem-malik",
    name: "Saleem Malik",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "batsman",
    batting: 86,
    bowling: 10,
    blurb: "Crafty run-scoring with late-innings flexibility.",
  },
  {
    id: "ijaz-ahmed",
    name: "Ijaz Ahmed",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "batsman",
    batting: 81,
    bowling: 8,
    blurb: "Explosive range when Pakistan wanted to accelerate quickly.",
  },
  {
    id: "mushtaq-ahmed",
    name: "Mushtaq Ahmed",
    squadId: "pakistan-1992",
    team: "Pakistan",
    year: 1992,
    role: "bowler",
    batting: 22,
    bowling: 80,
    blurb: "Wrist-spin variation for a pace-heavy tournament side.",
  },
  {
    id: "arjuna-ranatunga",
    name: "Arjuna Ranatunga",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "batsman",
    batting: 86,
    bowling: 18,
    blurb: "Leadership and left-handed batting built for chases.",
  },
  {
    id: "roshan-mahanama",
    name: "Roshan Mahanama",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "batsman",
    batting: 79,
    bowling: 8,
    blurb: "Measured batting that let the hitters work around him.",
  },
  {
    id: "hashan-tillakaratne",
    name: "Hashan Tillakaratne",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "batsman",
    batting: 80,
    bowling: 14,
    blurb: "Compact batting and calm middle-order management.",
  },
  {
    id: "kumar-dharmasena",
    name: "Kumar Dharmasena",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "bowler",
    batting: 68,
    bowling: 75,
    blurb: "Useful all-round balance through tidy spin and smart batting.",
  },
  {
    id: "pramodya-wickramasinghe",
    name: "Pramodya Wickramasinghe",
    squadId: "sri-lanka-1996",
    team: "Sri Lanka",
    year: 1996,
    role: "bowler",
    batting: 24,
    bowling: 77,
    blurb: "New-ball seam support behind the bigger stars.",
  },
  {
    id: "richie-richardson",
    name: "Richie Richardson",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "batsman",
    batting: 85,
    bowling: 8,
    blurb: "Top-order authority and crisp off-side scoring.",
  },
  {
    id: "stuart-williams",
    name: "Stuart Williams",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "batsman",
    batting: 79,
    bowling: 10,
    blurb: "Steady ODI batting with enough tempo to keep the board moving.",
  },
  {
    id: "sherwin-campbell",
    name: "Sherwin Campbell",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "batsman",
    batting: 78,
    bowling: 8,
    blurb: "An opener who gave the lineup sturdier starts when needed.",
  },
  {
    id: "roger-harper",
    name: "Roger Harper",
    squadId: "west-indies-1996",
    team: "West Indies",
    year: 1996,
    role: "bowler",
    batting: 65,
    bowling: 76,
    blurb: "Off-spin control and practical lower-order runs.",
  },
  {
    id: "mark-waugh",
    name: "Mark Waugh",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "batsman",
    batting: 89,
    bowling: 28,
    blurb: "Touch batting that made ODI strokeplay look effortless.",
  },
  {
    id: "shane-lee",
    name: "Shane Lee",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "bowler",
    batting: 72,
    bowling: 77,
    blurb: "Seam-up support with useful batting depth.",
  },
  {
    id: "tom-moody",
    name: "Tom Moody",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "batsman",
    batting: 78,
    bowling: 72,
    blurb: "Height, match-up flexibility, and handy seam overs.",
  },
  {
    id: "paul-reiffel",
    name: "Paul Reiffel",
    squadId: "australia-1999",
    team: "Australia",
    year: 1999,
    role: "bowler",
    batting: 34,
    bowling: 82,
    blurb: "Steady seam bowling that kept pressure on the middle overs.",
  },
  {
    id: "gary-kirsten",
    name: "Gary Kirsten",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "batsman",
    batting: 88,
    bowling: 8,
    blurb: "An ODI opening organiser with strong conversion power.",
  },
  {
    id: "daryll-cullinan",
    name: "Daryll Cullinan",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "batsman",
    batting: 84,
    bowling: 6,
    blurb: "Classical middle-order batting with serious range square of the wicket.",
  },
  {
    id: "nicky-boje",
    name: "Nicky Boje",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "bowler",
    batting: 69,
    bowling: 78,
    blurb: "Left-arm spin and practical lower-order batting.",
  },
  {
    id: "steve-elworthy",
    name: "Steve Elworthy",
    squadId: "south-africa-1999",
    team: "South Africa",
    year: 1999,
    role: "bowler",
    batting: 28,
    bowling: 81,
    blurb: "Reliable seam support in a very deep attack.",
  },
  {
    id: "gautam-gambhir",
    name: "Gautam Gambhir",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "batsman",
    batting: 90,
    bowling: 8,
    blurb: "An innings builder who kept big finals from tilting.",
  },
  {
    id: "suresh-raina",
    name: "Suresh Raina",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "batsman",
    batting: 84,
    bowling: 68,
    blurb: "Finishing acceleration with useful part-time spin.",
  },
  {
    id: "yusuf-pathan",
    name: "Yusuf Pathan",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "batsman",
    batting: 82,
    bowling: 71,
    blurb: "Six-hitting muscle and occasional off-spin utility.",
  },
  {
    id: "munaf-patel",
    name: "Munaf Patel",
    squadId: "india-2011",
    team: "India",
    year: 2011,
    role: "bowler",
    batting: 18,
    bowling: 78,
    blurb: "Hit-the-deck seam support that held lanes well.",
  },
  {
    id: "aaron-finch",
    name: "Aaron Finch",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "batsman",
    batting: 89,
    bowling: 6,
    blurb: "Power and tempo that set aggressive ODI terms up front.",
  },
  {
    id: "george-bailey",
    name: "George Bailey",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "batsman",
    batting: 82,
    bowling: 8,
    blurb: "Middle-order management with clean hitting zones.",
  },
  {
    id: "shane-watson",
    name: "Shane Watson",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "batsman",
    batting: 87,
    bowling: 78,
    blurb: "Power and seam control in one sturdy ODI frame.",
  },
  {
    id: "pat-cummins",
    name: "Pat Cummins",
    squadId: "australia-2015",
    team: "Australia",
    year: 2015,
    role: "bowler",
    batting: 34,
    bowling: 84,
    blurb: "Skiddy pace and high-pressure overs on demand.",
  },
  {
    id: "henry-nicholls",
    name: "Henry Nicholls",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "batsman",
    batting: 81,
    bowling: 8,
    blurb: "Left-handed stability and good rotation through the middle.",
  },
  {
    id: "colin-de-grandhomme",
    name: "Colin de Grandhomme",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "bowler",
    batting: 76,
    bowling: 76,
    blurb: "A complete white-ball utility piece with seam-up value.",
  },
  {
    id: "matt-henry",
    name: "Matt Henry",
    squadId: "new-zealand-2019",
    team: "New Zealand",
    year: 2019,
    role: "bowler",
    batting: 24,
    bowling: 85,
    blurb: "New-ball seam and hard-length discipline.",
  },
  {
    id: "jonny-bairstow",
    name: "Jonny Bairstow",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "batsman",
    batting: 91,
    bowling: 6,
    blurb: "Powerplay pressure and boundary pressure from the first over.",
  },
  {
    id: "liam-plunkett",
    name: "Liam Plunkett",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "bowler",
    batting: 30,
    bowling: 83,
    blurb: "A middle-overs wicket-taker who disrupted set batters.",
  },
  {
    id: "mark-wood",
    name: "Mark Wood",
    squadId: "england-2019",
    team: "England",
    year: 2019,
    role: "bowler",
    batting: 18,
    bowling: 86,
    blurb: "Express pace that changed the speed of an innings.",
  },
  {
    id: "litton-das",
    name: "Litton Das",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "batsman",
    batting: 83,
    bowling: 6,
    blurb: "A free-flowing bat who could lift Bangladesh's ceiling quickly.",
  },
  {
    id: "soumya-sarkar",
    name: "Soumya Sarkar",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "batsman",
    batting: 80,
    bowling: 26,
    blurb: "Tempo-start batting with occasional seam-up utility.",
  },
  {
    id: "mehidy-hasan-miraz",
    name: "Mehidy Hasan Miraz",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "bowler",
    batting: 74,
    bowling: 79,
    blurb: "A strong balance pick with off-spin and real batting value.",
  },
  {
    id: "rubel-hossain",
    name: "Rubel Hossain",
    squadId: "bangladesh-2019",
    team: "Bangladesh",
    year: 2019,
    role: "bowler",
    batting: 20,
    bowling: 78,
    blurb: "Skiddy pace and wicket-taking bursts when Bangladesh needed them.",
  },
  {
    id: "virat-kohli-2023",
    name: "Virat Kohli",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "batsman",
    batting: 95,
    bowling: 8,
    blurb: "Chase control and ODI accumulation at all-time levels.",
  },
  {
    id: "ravichandran-ashwin",
    name: "Ravichandran Ashwin",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "bowler",
    batting: 66,
    bowling: 82,
    blurb: "Experience, matchup spin, and handy batting depth.",
  },
  {
    id: "kuldeep-yadav",
    name: "Kuldeep Yadav",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "bowler",
    batting: 18,
    bowling: 89,
    blurb: "A wrist-spinner who keeps buying wickets, not just dots.",
  },
  {
    id: "mohammed-siraj",
    name: "Mohammed Siraj",
    squadId: "india-2023",
    team: "India",
    year: 2023,
    role: "bowler",
    batting: 18,
    bowling: 87,
    blurb: "New-ball aggression with seam movement at full pace.",
  },
  {
    id: "imam-ul-haq",
    name: "Imam-ul-Haq",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "batsman",
    batting: 85,
    bowling: 6,
    blurb: "A left-handed ODI anchor with strong volume scoring.",
  },
  {
    id: "abdullah-shafique",
    name: "Abdullah Shafique",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "batsman",
    batting: 83,
    bowling: 6,
    blurb: "Elegant pace play and calm top-order tempo.",
  },
  {
    id: "mohammad-nawaz",
    name: "Mohammad Nawaz",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "bowler",
    batting: 75,
    bowling: 76,
    blurb: "Spin-bowling balance with genuine lower-order batting.",
  },
  {
    id: "hasan-ali",
    name: "Hasan Ali",
    squadId: "pakistan-2023",
    team: "Pakistan",
    year: 2023,
    role: "bowler",
    batting: 38,
    bowling: 81,
    blurb: "Busy seam bowling and a knack for picking momentum wickets.",
  },
  {
    id: "rahmat-shah",
    name: "Rahmat Shah",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "batsman",
    batting: 82,
    bowling: 8,
    blurb: "A composed ODI bat who gives Afghanistan shape around the hitters.",
  },
  {
    id: "azmatullah-omarzai",
    name: "Azmatullah Omarzai",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "bowler",
    batting: 78,
    bowling: 75,
    blurb: "A true white-ball all-round asset with pace-off variation.",
  },
  {
    id: "ikram-alikhil",
    name: "Ikram Alikhil",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "wicketkeeper",
    batting: 76,
    bowling: 0,
    blurb: "Backup keeper-batter depth with calm accumulation.",
  },
  {
    id: "fazalhaq-farooqi",
    name: "Fazalhaq Farooqi",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "bowler",
    batting: 18,
    bowling: 83,
    blurb: "Left-arm seam and powerplay movement from a tough release angle.",
  },
  {
    id: "naveen-ul-haq",
    name: "Naveen-ul-Haq",
    squadId: "afghanistan-2023",
    team: "Afghanistan",
    year: 2023,
    role: "bowler",
    batting: 20,
    bowling: 82,
    blurb: "Death-overs variation and wicket-taking intent.",
  },
  {
    id: "alistair-campbell",
    name: "Alistair Campbell",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "batsman",
    batting: 83,
    bowling: 8,
    blurb: "An organizer at the top with enough range to set ODI tempo.",
  },
  {
    id: "grant-flower",
    name: "Grant Flower",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "batsman",
    batting: 84,
    bowling: 66,
    blurb: "Stylish batting with useful spin when overs needed filling.",
  },
  {
    id: "andy-flower",
    name: "Andy Flower",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "wicketkeeper",
    batting: 92,
    bowling: 0,
    blurb: "A world-class keeper-batter and easily Zimbabwe's elite ODI anchor.",
  },
  {
    id: "neil-johnson",
    name: "Neil Johnson",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "batsman",
    batting: 87,
    bowling: 79,
    blurb: "A proper World Cup all-round force who could change matches himself.",
  },
  {
    id: "murray-goodwin",
    name: "Murray Goodwin",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "batsman",
    batting: 82,
    bowling: 12,
    blurb: "Smooth middle-order batting built for longer one-day innings.",
  },
  {
    id: "stuart-carlisle",
    name: "Stuart Carlisle",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "batsman",
    batting: 79,
    bowling: 10,
    blurb: "Steady ODI batting that could keep a chase from wobbling.",
  },
  {
    id: "guy-whittall",
    name: "Guy Whittall",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "batsman",
    batting: 76,
    bowling: 62,
    blurb: "Handy batting and support overs that made balance easier.",
  },
  {
    id: "heath-streak",
    name: "Heath Streak",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "bowler",
    batting: 71,
    bowling: 88,
    blurb: "Leader, strike seamer, and one of Zimbabwe's ODI greats.",
  },
  {
    id: "henry-olonga",
    name: "Henry Olonga",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "bowler",
    batting: 22,
    bowling: 80,
    blurb: "Skiddy pace and wicket-taking bursts when rhythm clicked.",
  },
  {
    id: "eddo-brandes",
    name: "Eddo Brandes",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "bowler",
    batting: 30,
    bowling: 77,
    blurb: "Accurate seam bowling with veteran ODI nous.",
  },
  {
    id: "paul-strang",
    name: "Paul Strang",
    squadId: "zimbabwe-1999",
    team: "Zimbabwe",
    year: 1999,
    role: "bowler",
    batting: 68,
    bowling: 79,
    blurb: "A balanced spin-bowling option with very useful batting depth.",
  },
  {
    id: "steve-tikolo",
    name: "Steve Tikolo",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "batsman",
    batting: 88,
    bowling: 28,
    blurb: "Kenya's batting brain and the center of that famous World Cup run.",
  },
  {
    id: "kennedy-otieno",
    name: "Kennedy Otieno",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "wicketkeeper",
    batting: 76,
    bowling: 0,
    blurb: "Functional ODI keeper-batting that helped stabilize starts.",
  },
  {
    id: "ravindu-shah",
    name: "Ravindu Shah",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "batsman",
    batting: 79,
    bowling: 12,
    blurb: "Compact opening batting with a strong value on patience.",
  },
  {
    id: "brijal-patel",
    name: "Brijal Patel",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "batsman",
    batting: 74,
    bowling: 8,
    blurb: "A top-order option who could hold shape under pressure.",
  },
  {
    id: "hitesh-modi",
    name: "Hitesh Modi",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "batsman",
    batting: 75,
    bowling: 16,
    blurb: "Middle-order glue for attritional ODI innings.",
  },
  {
    id: "maurice-odumbe",
    name: "Maurice Odumbe",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "batsman",
    batting: 77,
    bowling: 68,
    blurb: "Off-spin utility and inventive batting in the middle overs.",
  },
  {
    id: "thomas-odoyo",
    name: "Thomas Odoyo",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "bowler",
    batting: 76,
    bowling: 77,
    blurb: "An important seam-bowling all-round piece in Kenya's structure.",
  },
  {
    id: "collins-obuya",
    name: "Collins Obuya",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "bowler",
    batting: 54,
    bowling: 80,
    blurb: "Leg-spin wicket bursts made him one of the tournament stories.",
  },
  {
    id: "martin-suji",
    name: "Martin Suji",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "bowler",
    batting: 30,
    bowling: 78,
    blurb: "Hit-the-deck seam bowling with experienced control.",
  },
  {
    id: "peter-ongondo",
    name: "Peter Ongondo",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "bowler",
    batting: 22,
    bowling: 76,
    blurb: "Powerplay seam support with honest ODI discipline.",
  },
  {
    id: "joseph-angara",
    name: "Joseph Angara",
    squadId: "kenya-2003",
    team: "Kenya",
    year: 2003,
    role: "bowler",
    batting: 20,
    bowling: 74,
    blurb: "Seam bowling depth that completed Kenya's semifinal attack.",
  },
  {
    id: "irving-romaine",
    name: "Irving Romaine",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "batsman",
    batting: 76,
    bowling: 18,
    blurb: "A captain who kept Bermuda's batting orderly and competitive.",
  },
  {
    id: "oliver-pitcher",
    name: "Oliver Pitcher",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "batsman",
    batting: 74,
    bowling: 8,
    blurb: "Top-order ballast for a historic associate qualifier.",
  },
  {
    id: "janeiro-tucker",
    name: "Janeiro Tucker",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "batsman",
    batting: 75,
    bowling: 22,
    blurb: "A busy middle-order bat who kept pressure off teammates.",
  },
  {
    id: "david-hemp",
    name: "David Hemp",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "batsman",
    batting: 82,
    bowling: 26,
    blurb: "The most polished batting name in Bermuda's World Cup side.",
  },
  {
    id: "lionel-cann",
    name: "Lionel Cann",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "batsman",
    batting: 77,
    bowling: 24,
    blurb: "A forceful hitter who brought real ODI intent.",
  },
  {
    id: "dean-minors",
    name: "Dean Minors",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "wicketkeeper",
    batting: 72,
    bowling: 0,
    blurb: "An experienced keeper who helped steady lower-order phases.",
  },
  {
    id: "malachi-jones",
    name: "Malachi Jones",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "bowler",
    batting: 34,
    bowling: 76,
    blurb: "Athletic seam bowling and some late-order hitting.",
  },
  {
    id: "dwayne-leverock",
    name: "Dwayne Leverock",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "bowler",
    batting: 38,
    bowling: 75,
    blurb: "Left-arm spin and cult-hero energy for the associate stage.",
  },
  {
    id: "kevin-hurdle",
    name: "Kevin Hurdle",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "bowler",
    batting: 28,
    bowling: 74,
    blurb: "Seam support built more on control than pace.",
  },
  {
    id: "stefan-kelly",
    name: "Stefan Kelly",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "bowler",
    batting: 24,
    bowling: 73,
    blurb: "A steady seam option in Bermuda's historic squad.",
  },
  {
    id: "saleem-mukuddem",
    name: "Saleem Mukuddem",
    squadId: "bermuda-2007",
    team: "Bermuda",
    year: 2007,
    role: "bowler",
    batting: 26,
    bowling: 72,
    blurb: "Lower-order effort and bowling depth in the associate tier.",
  },
  {
    id: "ashish-bagai",
    name: "Ashish Bagai",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "wicketkeeper",
    batting: 81,
    bowling: 0,
    blurb: "Canada's smartest batting organiser and a dependable keeper.",
  },
  {
    id: "john-davison",
    name: "John Davison",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "batsman",
    batting: 84,
    bowling: 64,
    blurb: "Big-hitting history and some useful off-spin on the side.",
  },
  {
    id: "rizwan-cheema",
    name: "Rizwan Cheema",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "batsman",
    batting: 82,
    bowling: 12,
    blurb: "A powerful bat who could alter the rate quickly.",
  },
  {
    id: "zubin-surkari",
    name: "Zubin Surkari",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "batsman",
    batting: 76,
    bowling: 18,
    blurb: "Middle-order batting built for rescue jobs.",
  },
  {
    id: "jimmy-hansra",
    name: "Jimmy Hansra",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "batsman",
    batting: 77,
    bowling: 10,
    blurb: "A left-hander who gave Canada's lineup some shape.",
  },
  {
    id: "nitish-kumar",
    name: "Nitish Kumar",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "batsman",
    batting: 74,
    bowling: 8,
    blurb: "A young top-order bat with long-format composure in ODI tempo.",
  },
  {
    id: "hiral-patel",
    name: "Hiral Patel",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "batsman",
    batting: 75,
    bowling: 8,
    blurb: "Aggressive intent at the top for a developing side.",
  },
  {
    id: "balaji-rao",
    name: "Balaji Rao",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "bowler",
    batting: 26,
    bowling: 79,
    blurb: "Finger-spin control with good one-day discipline.",
  },
  {
    id: "harvir-baidwan",
    name: "Harvir Baidwan",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "bowler",
    batting: 48,
    bowling: 76,
    blurb: "Useful seam-bowling all-round depth for Canada.",
  },
  {
    id: "khurram-chohan",
    name: "Khurram Chohan",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "bowler",
    batting: 24,
    bowling: 77,
    blurb: "Skiddy seam bowling with effort and wicket-taking intent.",
  },
  {
    id: "henry-osinde",
    name: "Henry Osinde",
    squadId: "canada-2011",
    team: "Canada",
    year: 2011,
    role: "bowler",
    batting: 22,
    bowling: 75,
    blurb: "Left-arm seam and hard work through the powerplay.",
  },
  {
    id: "william-porterfield",
    name: "William Porterfield",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "batsman",
    batting: 85,
    bowling: 12,
    blurb: "Captaincy and crisp ODI opening play with real substance.",
  },
  {
    id: "paul-stirling",
    name: "Paul Stirling",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "batsman",
    batting: 88,
    bowling: 18,
    blurb: "One of Ireland's most dangerous white-ball batters.",
  },
  {
    id: "ed-joyce",
    name: "Ed Joyce",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "batsman",
    batting: 84,
    bowling: 8,
    blurb: "A polished left-hander built for ODI tempo control.",
  },
  {
    id: "niall-obrien",
    name: "Niall O'Brien",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "wicketkeeper",
    batting: 80,
    bowling: 0,
    blurb: "A wicketkeeper-batter who could keep the innings moving.",
  },
  {
    id: "kevin-obrien",
    name: "Kevin O'Brien",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "batsman",
    batting: 86,
    bowling: 74,
    blurb: "World Cup legend status for the fastest ton and real seam utility.",
  },
  {
    id: "gary-wilson",
    name: "Gary Wilson",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "batsman",
    batting: 77,
    bowling: 0,
    blurb: "Flexible batting cover who deepened Ireland's options.",
  },
  {
    id: "alex-cusack",
    name: "Alex Cusack",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "bowler",
    batting: 73,
    bowling: 75,
    blurb: "A genuine utility all-rounder across all ODI phases.",
  },
  {
    id: "john-mooney",
    name: "John Mooney",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "bowler",
    batting: 71,
    bowling: 76,
    blurb: "Left-arm seam and batting grit for long days.",
  },
  {
    id: "george-dockrell",
    name: "George Dockrell",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "bowler",
    batting: 46,
    bowling: 79,
    blurb: "Left-arm spin that kept Ireland in middle-overs contests.",
  },
  {
    id: "boyd-rankin",
    name: "Boyd Rankin",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "bowler",
    batting: 24,
    bowling: 82,
    blurb: "Height, bounce, and serious wicket-taking quality for an associate side.",
  },
  {
    id: "trent-johnston",
    name: "Trent Johnston",
    squadId: "ireland-2011",
    team: "Ireland",
    year: 2011,
    role: "bowler",
    batting: 20,
    bowling: 78,
    blurb: "Veteran seam leadership with strong new-ball skills.",
  },
  {
    id: "kyle-coetzer",
    name: "Kyle Coetzer",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "batsman",
    batting: 85,
    bowling: 10,
    blurb: "A classy ODI opener who gave Scotland real top-order certainty.",
  },
  {
    id: "calum-macleod",
    name: "Calum MacLeod",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "batsman",
    batting: 84,
    bowling: 20,
    blurb: "One of Scotland's most accomplished white-ball run-makers.",
  },
  {
    id: "preston-mommsen",
    name: "Preston Mommsen",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "batsman",
    batting: 82,
    bowling: 12,
    blurb: "Captaincy and compact batting for long one-day innings.",
  },
  {
    id: "richie-berrington",
    name: "Richie Berrington",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "batsman",
    batting: 81,
    bowling: 22,
    blurb: "Middle-order power and useful overs if the matchup suited.",
  },
  {
    id: "matt-machan",
    name: "Matt Machan",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "batsman",
    batting: 76,
    bowling: 8,
    blurb: "Left-handed structure to Scotland's batting card.",
  },
  {
    id: "matt-cross",
    name: "Matt Cross",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "wicketkeeper",
    batting: 74,
    bowling: 0,
    blurb: "A developing keeper-batter who filled a key squad role.",
  },
  {
    id: "majid-haq",
    name: "Majid Haq",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "bowler",
    batting: 66,
    bowling: 77,
    blurb: "Off-spin control and some useful batting depth.",
  },
  {
    id: "josh-davey",
    name: "Josh Davey",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "bowler",
    batting: 30,
    bowling: 78,
    blurb: "Seam bowling with a strong work rate and ODI discipline.",
  },
  {
    id: "iain-wardlaw",
    name: "Iain Wardlaw",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "bowler",
    batting: 18,
    bowling: 76,
    blurb: "Fast-bowling aggression that gave Scotland real edge.",
  },
  {
    id: "alasdair-evans",
    name: "Alasdair Evans",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "bowler",
    batting: 22,
    bowling: 77,
    blurb: "Seam support with consistent powerplay effort.",
  },
  {
    id: "safyaan-sharif",
    name: "Safyaan Sharif",
    squadId: "scotland-2015",
    team: "Scotland",
    year: 2015,
    role: "bowler",
    batting: 28,
    bowling: 79,
    blurb: "A dependable seam option who stayed in the fight deep into spells.",
  },
  {
    id: "khurram-khan",
    name: "Khurram Khan",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "batsman",
    batting: 86,
    bowling: 24,
    blurb: "An experienced ODI accumulator and the center of UAE batting plans.",
  },
  {
    id: "shaiman-anwar",
    name: "Shaiman Anwar",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "batsman",
    batting: 84,
    bowling: 8,
    blurb: "Aggression and range through the top and middle overs.",
  },
  {
    id: "swapnil-patil",
    name: "Swapnil Patil",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "wicketkeeper",
    batting: 80,
    bowling: 0,
    blurb: "A busy keeper-batter who helped UAE stay composed.",
  },
  {
    id: "andri-berenger",
    name: "Andri Berenger",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "batsman",
    batting: 76,
    bowling: 8,
    blurb: "Young batting energy and clean striking in spurts.",
  },
  {
    id: "rohan-mustafa",
    name: "Rohan Mustafa",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "batsman",
    batting: 79,
    bowling: 74,
    blurb: "A very useful all-round presence across all phases.",
  },
  {
    id: "mohammad-tauqir",
    name: "Mohammad Tauqir",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "batsman",
    batting: 74,
    bowling: 72,
    blurb: "Captaincy and off-spin value behind a practical batting approach.",
  },
  {
    id: "amjad-javed",
    name: "Amjad Javed",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "bowler",
    batting: 72,
    bowling: 78,
    blurb: "Seam-bowling all-round strength and emotional energy.",
  },
  {
    id: "nasir-aziz",
    name: "Nasir Aziz",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "bowler",
    batting: 44,
    bowling: 77,
    blurb: "Off-spin control and accurate middle-overs work.",
  },
  {
    id: "manjula-guruge",
    name: "Manjula Guruge",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "bowler",
    batting: 28,
    bowling: 75,
    blurb: "A seamer who brought persistence more than headline pace.",
  },
  {
    id: "kamran-shahzad",
    name: "Kamran Shahzad",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "bowler",
    batting: 26,
    bowling: 74,
    blurb: "Support seam bowling in a scrappy associate attack.",
  },
  {
    id: "sohail-khan-uae",
    name: "Sohail Khan",
    squadId: "uae-2015",
    team: "United Arab Emirates",
    year: 2015,
    role: "bowler",
    batting: 24,
    bowling: 73,
    blurb: "A depth seamer who completed UAE's bowling unit.",
  },
  {
    id: "deon-kotze",
    name: "Deon Kotze",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "wicketkeeper",
    batting: 74,
    bowling: 0,
    blurb: "Captain and keeper-batter at the center of Namibia's first World Cup.",
  },
  {
    id: "danie-keulder",
    name: "Danie Keulder",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "batsman",
    batting: 77,
    bowling: 12,
    blurb: "Top-order batting with genuine ODI tempo for an associate side.",
  },
  {
    id: "jan-berrie-burger",
    name: "Jan-Berrie Burger",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "batsman",
    batting: 79,
    bowling: 18,
    blurb: "The standout batting talent in that Namibian generation.",
  },
  {
    id: "gerrie-snyman",
    name: "Gerrie Snyman",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "batsman",
    batting: 76,
    bowling: 20,
    blurb: "Hard-hitting batting that could change the feel of a chase.",
  },
  {
    id: "sarel-burger",
    name: "Sarel Burger",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "batsman",
    batting: 74,
    bowling: 68,
    blurb: "A useful dual-skill option for one-day balance.",
  },
  {
    id: "louis-burger",
    name: "Louis Burger",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "batsman",
    batting: 72,
    bowling: 22,
    blurb: "Lower-middle batting support with some useful resistance.",
  },
  {
    id: "gavin-murgatroyd",
    name: "Gavin Murgatroyd",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "bowler",
    batting: 68,
    bowling: 76,
    blurb: "One of Namibia's more rounded all-round cricketing profiles.",
  },
  {
    id: "rudi-van-vuuren",
    name: "Rudi van Vuuren",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "bowler",
    batting: 30,
    bowling: 78,
    blurb: "Seam bowling grit from the World Cup's famously multi-talented doctor.",
  },
  {
    id: "bjorn-kotze",
    name: "Bjorn Kotze",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "bowler",
    batting: 26,
    bowling: 74,
    blurb: "Pace support in a side learning quickly at the top level.",
  },
  {
    id: "melt-van-schoor",
    name: "Melt van Schoor",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "bowler",
    batting: 24,
    bowling: 73,
    blurb: "Seam depth and workmanlike ODI spells for Namibia.",
  },
  {
    id: "andre-van-schoor",
    name: "Andre van Schoor",
    squadId: "namibia-2003",
    team: "Namibia",
    year: 2003,
    role: "bowler",
    batting: 42,
    bowling: 72,
    blurb: "Veteran know-how and support overs in Namibia's breakthrough squad.",
  },
  {
    id: "scott-edwards",
    name: "Scott Edwards",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "wicketkeeper",
    batting: 84,
    bowling: 0,
    blurb: "Calm leadership and sharp keeping for the modern Dutch side.",
  },
  {
    id: "max-odowd",
    name: "Max O'Dowd",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "batsman",
    batting: 82,
    bowling: 10,
    blurb: "Top-order tempo and clean power through the V.",
  },
  {
    id: "vikramjit-singh",
    name: "Vikramjit Singh",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "batsman",
    batting: 80,
    bowling: 8,
    blurb: "A young top-order bat with range and ambition.",
  },
  {
    id: "bas-de-leede",
    name: "Bas de Leede",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "batsman",
    batting: 83,
    bowling: 79,
    blurb: "A complete white-ball all-round package and a huge Dutch asset.",
  },
  {
    id: "teja-nidamanuru",
    name: "Teja Nidamanuru",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "batsman",
    batting: 81,
    bowling: 12,
    blurb: "Middle-order hitting and calm finishing instincts.",
  },
  {
    id: "colin-ackermann",
    name: "Colin Ackermann",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "batsman",
    batting: 82,
    bowling: 72,
    blurb: "A very useful ODI all-round stabilizer with matchup flexibility.",
  },
  {
    id: "sybrand-engelbrecht",
    name: "Sybrand Engelbrecht",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "batsman",
    batting: 79,
    bowling: 14,
    blurb: "Middle-order strokeplay and athletic white-ball instincts.",
  },
  {
    id: "logan-van-beek",
    name: "Logan van Beek",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "bowler",
    batting: 73,
    bowling: 78,
    blurb: "A highly useful seam-bowling all-rounder in the modern Dutch setup.",
  },
  {
    id: "roelof-van-der-merwe",
    name: "Roelof van der Merwe",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "bowler",
    batting: 72,
    bowling: 80,
    blurb: "Left-arm spin, edge, and veteran one-day value.",
  },
  {
    id: "aryan-dutt",
    name: "Aryan Dutt",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "bowler",
    batting: 22,
    bowling: 77,
    blurb: "Off-spin control that fits nicely into ODI middle overs.",
  },
  {
    id: "paul-van-meekeren",
    name: "Paul van Meekeren",
    squadId: "netherlands-2023",
    team: "Netherlands",
    year: 2023,
    role: "bowler",
    batting: 20,
    bowling: 82,
    blurb: "Aggressive seam bowling with visible competitive bite.",
  },
];
